### ISSUE TITLE
crashes with invalid data at fetch

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/nodebb-plugin-ntfy#6]
```
2023-01-19T21:01:35.342Z [4568/3992311] - [31merror[39m: TypeError: omega has posted a reply to: 🤫 Pre-release previews of new theme design is not a legal HTTP header value
    at validateValue (/home/saas/nodebb/node_modules/node-fetch/lib/index.js:684:9)
    at Headers.append (/home/saas/nodebb/node_modules/node-fetch/lib/index.js:836:3)
    at new Headers (/home/saas/nodebb/node_modules/node-fetch/lib/index.js:761:11)
    at new Request (/home/saas/nodebb/node_modules/node-fetch/lib/index.js:1231:19)
    at /home/saas/nodebb/node_modules/node-fetch/lib/index.js:1453:19
    at new Promise (<anonymous>)
    at fetch (/home/saas/nodebb/node_modules/node-fetch/lib/index.js:1451:9)
    at /home/saas/nodebb/node_modules/nodebb-plugin-ntfy/lib/ntfy.js:36:9
    at Array.map (<anonymous>)
    at Object.ntfy.send (/home/saas/nodebb/node_modules/nodebb-plugin-ntfy/lib/ntfy.js:35:27)
```

**Comment by barisusakli** [comment]
above commit prevents the crash but some titles like the above won't generate push notifs, guess emoji not allowed in header 😆
